### PR TITLE
Added detection of Chrome path for Windows

### PR DESCRIPTION
**Pull request by joeribekker**

### CODE REVIEW

**Comment by ckinsey** [comment]
@joeribekker Code looks good to me.  I don't have a windows machine up and running to test it, but I assume that's the standard path and you can count on the `ProgramFiles` environment var being set?

**Comment by joeribekker** [comment]
Well, now that you mention it. This would only work on a 32 bit Python with a 32 bit Chrome or if both are 64 bit... I'll add the mixed combinations as well. Sigh, Windows.

**Comment by bparker06** [comment]
Many Chrome installations on Windows are local to AppData these days as well, and don't use ProgramFiles.

**Comment by joeribekker** [comment]
@bparker06 I don't see that as a reason not to add it anyway. Chrome/Chromium on Linux can be in different places as well, with different executable names.

The detection looks in obvious places, if the executable is not found you need to set the `CHROME_PATH` argument.

**Comment by mattburlage** [comment]
This would be super helpful. Anything that can be done to help move this PR along? (Testing perhaps?)

**Comment by TyrelDenison** [comment]
@mattburlage Testing would be helpful yes. None of us at Lofty have a windows machine, so we cannot confirm it is working.

**Comment by bparker06** [comment]
There are many ways to run Windows from other hosts, whether locally via a virtual machine or remotely with a cloud service such as EC2 etc. Or is the real issue that you don't want to?

**Comment by TyrelDenison** [comment]
100% don't want to.

**Comment by TyrelDenison** [comment]
Presuming this to work at this point and merging. If the issue persists, we can create an issue.

**Pull request merged**
